image: node:10

stages:
  - build
  - image
  - release

build:
  stage: build
  image: registry.gitlab.com/stackworx-public/react-static-nginx/dnd_nodejs
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  tags:
    - docker
  cache:
    paths:
      - node_modules/
  script:
    - DOCKER_HOST=docker sh scripts/test.sh

build-image:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - tags
  tags:
    - docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - ./scripts/build.sh $CI_COMMIT_REF_NAME
    - ./scripts/push.sh $CI_COMMIT_REF_NAME

release:
  stage: release
  # when: manual
  tags:
    - docker
  dependencies:
  only:
    - master
  cache:
    paths:
      - node_modules/
  script:
    - yarn install --frozen-lockfile
    - yarn release
