image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
   - docker:dind

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/stackworx-public/react-static-nginx:1.13.11-r3 .
    - docker push registry.gitlab.com/stackworx-public/react-static-nginx:1.13.11-r3
