image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
   - docker:dind

build:
  script:
    - docker build -t registry.gitlab.com/stackworx.io/react-static-nginx:1.13.11 .
    - docker push registry.gitlab.com/stackworx.io/react-static-nginx:1.13.11
