image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
   - docker:dind

build:
  only:
   - master
  tags:
   - docker
   - linux
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/stackworx-public/react-static-nginx:1.15.2-r1 .
    - docker push registry.gitlab.com/stackworx-public/react-static-nginx:1.15.2-r1
