image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NGINX_VERSION: 1.15.2
  REVISION: r3

services:
   - docker:dind

build:
  only:
   - master
  tags:
   - docker
   - linux
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/stackworx-public/react-static-nginx:${NGINX_VERSION}-${REVISION} .
    - docker push registry.gitlab.com/stackworx-public/react-static-nginx:${NGINX_VERSION}-${REVISION}
