image: docker:latest

stages:
  - build
  - image
  - release

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - node_modules/
  script:
    - sh scripts/test.sh

build-image:
  stage: build
  only:
    - tags
  tags:
    - docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - ./scripts/build.sh $CI_COMMIT_REF_NAME
    - ./scripts/push.sh $CI_COMMIT_REF_NAME

release:
  stage: release
  when: manual
  tags:
    - docker
  dependencies:
  only:
    - master
  script:
    - yarn semantic-release
